name: Cache Prune

on:
  schedule:
    - cron: '0 3 * * 0' # Weekly Sunday 03:00 UTC
  workflow_dispatch: {}

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: List existing Actions caches (best-effort)
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.actions.getActionsCacheList({ owner: context.repo.owner, repo: context.repo.repo });
            core.info(`Found ${res.data.total_count} caches`);
            for (const c of res.data.actions_caches.slice(0,25)) {
              core.info(`Cache: key=${c.key} size=${c.size_in_bytes}`);
            }
      - name: Delete caches older than 30d (best-effort)
        uses: actions/github-script@v7
        with:
          script: |
            const cutoff = Date.now() - 1000*60*60*24*30;
            const res = await github.rest.actions.getActionsCacheList({ owner: context.repo.owner, repo: context.repo.repo });
            for (const c of res.data.actions_caches) {
              if (new Date(c.created_at).getTime() < cutoff) {
                try {
                  await github.rest.actions.deleteActionsCacheById({ owner: context.repo.owner, repo: context.repo.repo, cache_id: c.id });
                  core.info(`Deleted cache id=${c.id} key=${c.key}`);
                } catch (e) {
                  core.warning(`Could not delete cache id=${c.id}: ${e.message}`);
                }
              }
            }